name: build-test

on:
  push:
    branches: ["base", "develop/**"]
    paths: 
      - "src/**"
      - "include/**"
      - ".github/workflows/build-test.yaml"
  pull_request:
    branches: ["base"]

env:
  BUILD_TYPE: Release

jobs:
  build-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04]
    container:
      image: ghcr.io/cmaybe/dev-panda:latest
      options: --user root
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build
        run: |
          cmake -S . -B build -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}
          cmake --build build --config ${{ env.BUILD_TYPE }}

      